# Generated by Django 5.1.2 on 2024-10-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_assigned_to_record_last_updated_record_status_and_more'),
        ('website', 'create_user_profiles'),
    ]

    operations = [
    ]
